#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Valutapriser
graph_vlabel Kroner
graph_category other
graph_args -r -u 12 -l 4
graph_scale no
usd.label 1 USD
eur.label 1 EUR
sek.label 10 SEK
dkk.label 10 DKK
gbp.label 1 GBP
EOM
        exit 0;;
esac

echo -n "usd.value "
curl -s -A "Mozilla/4.0" "http://www.xe.com/currencyconverter/convert/?Amount=1&From=USD&To=NOK" | grep "rightCol" | grep "WARNING" | sed 's/<td width="47%" align="left" class="rightCol">//g' | sed 's/&nbsp;<span class="uccResCde">NOK<\/span><!-- WARNING: Automated extraction of rates is prohibited under the Terms of Use. -->//g' | egrep "[0-9].{1,}" -o

echo -n "eur.value "
curl -s -A "Mozilla/4.0" "http://www.xe.com/currencyconverter/convert/?Amount=1&From=EUR&To=NOK" | grep "rightCol" | grep "WARNING" | sed 's/<td width="47%" align="left" class="rightCol">//g' | sed 's/&nbsp;<span class="uccResCde">NOK<\/span><!-- WARNING: Automated extraction of rates is prohibited under the Terms of Use. -->//g' | egrep "[0-9].{1,}" -o

echo -n "sek.value "
curl -s -A "Mozilla/4.0" "http://www.xe.com/currencyconverter/convert/?Amount=1&From=SEK&To=NOK" | grep "rightCol" | grep "WARNING" | sed 's/<td width="47%" align="left" class="rightCol">//g' | sed 's/&nbsp;<span class="uccResCde">NOK<\/span><!-- WARNING: Automated extraction of rates is prohibited under the Terms of Use. -->//g' | egrep "[0-9].{1,}" -o

echo -n "dkk.value "
curl -s -A "Mozilla/4.0" "http://www.xe.com/currencyconverter/convert/?Amount=1&From=DKK&To=NOK" | grep "rightCol" | grep "WARNING" | sed 's/<td width="47%" align="left" class="rightCol">//g' | sed 's/&nbsp;<span class="uccResCde">NOK<\/span><!-- WARNING: Automated extraction of rates is prohibited under the Terms of Use. -->//g' | egrep "[0-9].{1,}" -o

echo -n "gbp.value "
curl -s -A "Mozilla/4.0" "http://www.xe.com/currencyconverter/convert/?Amount=1&From=GBP&To=NOK" | grep "rightCol" | grep "WARNING" | sed 's/<td width="47%" align="left" class="rightCol">//g' | sed 's/&nbsp;<span class="uccResCde">NOK<\/span><!-- WARNING: Automated extraction of rates is prohibited under the Terms of Use. -->//g' | egrep "[0-9].{1,}" -o
