#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Valutapriser
graph_vlabel Kroner
graph_category other
graph_args -r -u 12 -l 4
graph_scale no
usd.label 1 USD
eur.label 1 EUR
sek.label 10 SEK
dkk.label 10 DKK
gbp.label 1 GBP
EOM
        exit 0;;
esac

echo -n "usd.value "
curl -s -A "Mozilla/4.0" "http://www.xe.com/ucc/convert/?Amount=1&From=USD&To=NOK" | grep -i warning | grep -i nok | sed 's/<td width="46%" align="left">//g' | sed 's/&nbsp;NOK<!-- WARNING: Automated extraction of rates is prohibited under the Terms of Use. -->//g' | egrep "[0-9].{1,}" -o
echo -n "eur.value "
curl -s -A "Mozilla/4.0" "http://www.xe.com/ucc/convert/?Amount=1&From=EUR&To=NOK" | grep -i warning | grep -i nok | sed 's/<td width="46%" align="left">//g' | sed 's/&nbsp;NOK<!-- WARNING: Automated extraction of rates is prohibited under the Terms of Use. -->//g' | egrep "[0-9].{1,}" -o
echo -n "sek.value "
curl -s -A "Mozilla/4.0" "http://www.xe.com/ucc/convert/?Amount=10&From=SEK&To=NOK" | grep -i warning | grep -i nok | sed 's/<td width="46%" align="left">//g' | sed 's/&nbsp;NOK<!-- WARNING: Automated extraction of rates is prohibited under the Terms of Use. -->//g' | egrep "[0-9].{1,}" -o
echo -n "dkk.value "
curl -s -A "Mozilla/4.0" "http://www.xe.com/ucc/convert/?Amount=10&From=DKK&To=NOK" | grep -i warning | grep -i nok | sed 's/<td width="46%" align="left">//g' | sed 's/&nbsp;NOK<!-- WARNING: Automated extraction of rates is prohibited under the Terms of Use. -->//g' | egrep "[0-9].{1,}" -o
echo -n "gbp.value "
curl -s -A "Mozilla/4.0" "http://www.xe.com/ucc/convert/?Amount=1&From=GBP&To=NOK" | grep -i warning | grep -i nok | sed 's/<td width="46%" align="left">//g' | sed 's/&nbsp;NOK<!-- WARNING: Automated extraction of rates is prohibited under the Terms of Use. -->//g' | egrep "[0-9].{1,}" -o
